module.exports = {
  docs: [
    {
      type: "category",
      label: "Introduction",
      items: [
        "introduction/introduction",
        "introduction/contributing",
        "introduction/wallets",
        "introduction/dapps",
        "introduction/security-audit",
      ],
      collapsed: true,
    },
    {
      type: "category",
      label: "Getting Started",
      items: [
        "getting-started/installation",
        "getting-started/first-dapp",
        "getting-started/best-practices",
        "getting-started/simple-example",
        "getting-started/advanced-example",
        "getting-started/subscribe-to-active-account",
        "getting-started/high-performance",
      ],
      collapsed: false,
    },
    {
      type: "category",
      label: "Guides",
      items: [
        "guides/active-account",
        "guides/disconnecting-a-wallet",
        "guides/network",
        "guides/networking",
        "guides/request-permissions",
        "guides/sign-payload",
        "guides/broadcast-request",
        "guides/simple-contract-call",
        "guides/fa1.2-transfer",
        "guides/fa2-transfer",
        "guides/contract-error-handling",
        "guides/subscribe-to-event",
        "guides/WC-events",
        "guides/standalone-delegation",
        "guides/metrics",
        "guides/bug-report",
        "guides/migration-guide",
        "guides/ssr",
        "guides/failed-to-connect",
        "guides/how-to-contribute",
      ],
      collapsed: true,
    },
    {
      type: "category",
      label: "Advanced",
      items: [
        "advanced/ui-elements",
        "advanced/custom-block-explorer",
        "advanced/different-node",
        "advanced/debug-wallet",
        "advanced/sdk-info",
        {
          type: "category",
          label: "Flows",
          items: [
            "advanced/flows/connection",
            "advanced/flows/extension-communication",
            "advanced/flows/ledger-extension",
            "advanced/flows/local-mnemonic",
            "advanced/flows/p2p-direct",
            "advanced/flows/p2p-extension",
          ],
          collapsed: true,
        },
      ],
      collapsed: true,
    },
    {
      type: "category",
      label: "Messages",
      items: [
        "blockchains/introduction",
        "blockchains/usage",
        {
          type: "category",
          label: "Blockchains",
          items: [
            "blockchains/blockchain-substrate",
            "blockchains/blockchain-tezos",
            "blockchains/blockchain-tezos-sapling",
          ],
          collapsed: false,
        },
      ],
      collapsed: true,
    },
    {
      type: "category",
      label: "Post Mortem",
      items: [
        "post-mortem",
        "post-mortem-2",
        "post-mortem-3",
        "post-mortem-4",
        "post-mortem-5",
      ],
      collapsed: true,
    },
    {
      type: "link",
      label: "Changelog",
      href: "https://github.com/airgap-it/beacon-sdk/releases",
    },
    {
      type: "link",
      label: "TypeDoc Reference",
      href: "https://typedocs.walletbeacon.io",
    },
  ],
  wallet: [
    {
      type: "category",
      label: "Getting Started",
      items: [
        {
          type: "category",
          label: "Web",
          items: ["wallet/getting-started/web/getting-started"],
          collapsed: true,
        },
        {
          type: "category",
          label: "Android",
          items: [
            "wallet/getting-started/android/installation",
            "wallet/getting-started/android/connect-to-dapp",
            "wallet/getting-started/android/disconnect-from-dapp",
          ],
          collapsed: true,
        },
        {
          type: "category",
          label: "iOS",
          items: [
            "wallet/getting-started/ios/installation",
            "wallet/getting-started/ios/connect-to-dapp",
            "wallet/getting-started/ios/disconnect-from-dapp",
          ],
          collapsed: true,
        },
      ],
      collapsed: false,
    },
    {
      type: "category",
      label: "Advanced",
      items: [
        {
          type: "category",
          label: "Android",
          items: [
            "wallet/advanced/android/configuration",
            "wallet/advanced/android/coroutines-alternatives",
          ],
          collapsed: true,
        },
        {
          type: "category",
          label: "iOS",
          items: ["wallet/advanced/ios/configuration"],
          collapsed: true,
        },
      ],
      collapsed: false,
    },
    {
      type: "category",
      label: "Messages",
      items: ["wallet/messages/substrate", "wallet/messages/tezos"],
      collapsed: false,
    },
    "wallet/security",
  ],
};
